services:
  openems-ui-dev:
    image: ghcr.io/femumme/openems-ui-edge:latest
    container_name: openems_ui_dev
    hostname: openems-ui
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - openems-ui-conf:/etc/nginx:rw
      - openems-ui-log:/var/log/nginx:rw
    environment:
      - WEBSOCKET_HOST=host.docker.internal
      - WEBSOCKET_PORT=8075
    ports:
      - 4200:80

volumes:
  openems-ui-conf:
  openems-ui-log:
